/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreatorProfile {
  'id' : bigint,
  'bio' : string,
  'distanceLabel' : Type,
  'name' : string,
  'avatarUrl' : string,
  'category' : Type__1,
}
export type Type = { 'neighborhood' : null } |
  { 'hyperlocal' : null } |
  { 'cityWide' : null };
export type Type__1 = { 'art' : null } |
  { 'music' : null } |
  { 'food' : null } |
  { 'crafts' : null } |
  { 'wellness' : null } |
  { 'fashion' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCreator' : ActorMethod<[CreatorProfile], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllCreators' : ActorMethod<[], Array<CreatorProfile>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCreatorsByCategory' : ActorMethod<[Type__1], Array<CreatorProfile>>,
  'getCreatorsByDistanceLabel' : ActorMethod<[Type], Array<CreatorProfile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];