/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Type = IDL.Variant({
  'neighborhood' : IDL.Null,
  'hyperlocal' : IDL.Null,
  'cityWide' : IDL.Null,
});
export const Type__1 = IDL.Variant({
  'art' : IDL.Null,
  'music' : IDL.Null,
  'food' : IDL.Null,
  'crafts' : IDL.Null,
  'wellness' : IDL.Null,
  'fashion' : IDL.Null,
});
export const CreatorProfile = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'distanceLabel' : Type,
  'name' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'category' : Type__1,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const PublicUserProfile = IDL.Record({
  'username' : IDL.Text,
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCreator' : IDL.Func([CreatorProfile], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllCreators' : IDL.Func([], [IDL.Vec(CreatorProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCreatorsByCategory' : IDL.Func(
      [Type__1],
      [IDL.Vec(CreatorProfile)],
      ['query'],
    ),
  'getCreatorsByDistanceLabel' : IDL.Func(
      [Type],
      [IDL.Vec(CreatorProfile)],
      ['query'],
    ),
  'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      ['query'],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Type = IDL.Variant({
    'neighborhood' : IDL.Null,
    'hyperlocal' : IDL.Null,
    'cityWide' : IDL.Null,
  });
  const Type__1 = IDL.Variant({
    'art' : IDL.Null,
    'music' : IDL.Null,
    'food' : IDL.Null,
    'crafts' : IDL.Null,
    'wellness' : IDL.Null,
    'fashion' : IDL.Null,
  });
  const CreatorProfile = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'distanceLabel' : Type,
    'name' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'category' : Type__1,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const PublicUserProfile = IDL.Record({
    'username' : IDL.Text,
    'createdAt' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCreator' : IDL.Func([CreatorProfile], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllCreators' : IDL.Func([], [IDL.Vec(CreatorProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCreatorsByCategory' : IDL.Func(
        [Type__1],
        [IDL.Vec(CreatorProfile)],
        ['query'],
      ),
    'getCreatorsByDistanceLabel' : IDL.Func(
        [Type],
        [IDL.Vec(CreatorProfile)],
        ['query'],
      ),
    'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        ['query'],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };